Python 3.9.7 (v3.9.7:1016ef3790, Aug 30 2021, 16:39:15) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license()" for more information.
>>> import re
>>> import urllib.request as req
>>> resp=req.urlopen("https://www.python.org")
>>> text=resp.read()
>>> text=str(text,'utf8')
>>> tokens_by_re=re.split(r'\W+', text)  # split on regular expression r'\W+' (r stands for 'raw')
>>> print("len(tokens_by_re)")
len(tokens_by_re)
>>> print("Up to 100 tokens from tokens_from_re")
Up to 100 tokens from tokens_from_re
>>> print(tokens_by_re[:100])
['', 'doctype', 'html', 'if', 'lt', 'IE', '7', 'html', 'class', 'no', 'js', 'ie6', 'lt', 'ie7', 'lt', 'ie8', 'lt', 'ie9', 'endif', 'if', 'IE', '7', 'html', 'class', 'no', 'js', 'ie7', 'lt', 'ie8', 'lt', 'ie9', 'endif', 'if', 'IE', '8', 'html', 'class', 'no', 'js', 'ie8', 'lt', 'ie9', 'endif', 'if', 'gt', 'IE', '8', 'html', 'class', 'no', 'js', 'lang', 'en', 'dir', 'ltr', 'endif', 'head', 'meta', 'charset', 'utf', '8', 'meta', 'http', 'equiv', 'X', 'UA', 'Compatible', 'content', 'IE', 'edge', 'link', 'rel', 'prefetch', 'href', 'ajax', 'googleapis', 'com', 'ajax', 'libs', 'jquery', '1', '8', '2', 'jquery', 'min', 'js', 'link', 'rel', 'prefetch', 'href', 'ajax', 'googleapis', 'com', 'ajax', 'libs', 'jqueryui', '1', '12', '1', 'jquery']
>>> import pprint
>>> pprint.pprint(tokens_by_re[:100])
['',
 'doctype',
 'html',
 'if',
 'lt',
 'IE',
 '7',
 'html',
 'class',
 'no',
 'js',
 'ie6',
 'lt',
 'ie7',
 'lt',
 'ie8',
 'lt',
 'ie9',
 'endif',
 'if',
 'IE',
 '7',
 'html',
 'class',
 'no',
 'js',
 'ie7',
 'lt',
 'ie8',
 'lt',
 'ie9',
 'endif',
 'if',
 'IE',
 '8',
 'html',
 'class',
 'no',
 'js',
 'ie8',
 'lt',
 'ie9',
 'endif',
 'if',
 'gt',
 'IE',
 '8',
 'html',
 'class',
 'no',
 'js',
 'lang',
 'en',
 'dir',
 'ltr',
 'endif',
 'head',
 'meta',
 'charset',
 'utf',
 '8',
 'meta',
 'http',
 'equiv',
 'X',
 'UA',
 'Compatible',
 'content',
 'IE',
 'edge',
 'link',
 'rel',
 'prefetch',
 'href',
 'ajax',
 'googleapis',
 'com',
 'ajax',
 'libs',
 'jquery',
 '1',
 '8',
 '2',
 'jquery',
 'min',
 'js',
 'link',
 'rel',
 'prefetch',
 'href',
 'ajax',
 'googleapis',
 'com',
 'ajax',
 'libs',
 'jqueryui',
 '1',
 '12',
 '1',
 'jquery']
>>> 